import { useEffect, useState } from 'react';
import { CheckCircle2, FileText, MessageSquareReply, XCircle } from 'lucide-react';
import api from '../services/api';

const estados = { SOLICITADO: 'Solicitado', EN_REVISION: 'En revisión', APROBADO: 'Aprobado', RECHAZADO: 'Rechazado', CANCELADO: 'Cancelado' };
const filtros = [['TODOS', 'Todas'], ['EN_REVISION', 'En revisión'], ['SOLICITADO', 'Solicitado'], ['APROBADO', 'Aprobado'], ['RECHAZADO', 'Rechazado']];

export default function AdminVacations() {
  const [items, setItems] = useState([]); const [filtro, setFiltro] = useState('TODOS'); const [mensaje, setMensaje] = useState('');
  const cargar = async () => { try { const respuesta = await api.get('/admin/vacaciones/solicitudes'); setItems(respuesta.data); } catch { setMensaje('No fue posible cargar la bandeja de vacaciones.'); } };
  useEffect(() => {
    // react(set-state-in-effect) es intencional: carga datos remotos al montar.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    cargar();
  }, []);
  const actualizar = async (item, accion) => { const requiere = accion !== 'aprobar'; const motivo = window.prompt(requiere ? 'Motivo:' : 'Observación (opcional):'); if (requiere && !motivo) return; try { await api.post(`/admin/vacaciones/solicitudes/${item.id}/${accion}`, motivo ? { motivo } : {}); setMensaje(`Solicitud ${item.folio} actualizada.`); cargar(); } catch (error) { setMensaje(error.response?.data?.detail || 'No fue posible actualizar la solicitud.'); } };
  const visibles = filtro === 'TODOS' ? items : items.filter((item) => item.estado === filtro);
  return <div className="animate-in fade-in duration-500 space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Bandeja de vacaciones</h1><p className="mt-1 text-slate-500">Revisa solicitudes dentro de tu alcance departamental.</p></div>{mensaje && <div className="rounded-lg bg-blue-50 p-4 text-sm font-medium text-blue-700">{mensaje}</div>}<div className="flex flex-wrap gap-2 border-b border-slate-200">{filtros.map(([valor, etiqueta]) => <button key={valor} onClick={() => setFiltro(valor)} className={`border-b-2 px-4 py-2 text-sm font-medium ${filtro === valor ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-500'}`}>{etiqueta}</button>)}</div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm text-slate-600"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-4">Empleado</th><th className="px-6 py-4">Folio</th><th className="px-6 py-4">Fechas / días</th><th className="px-6 py-4">Estado</th><th className="px-6 py-4 text-right">Acciones</th></tr></thead><tbody>{visibles.map((item) => <tr key={item.id} className="border-b border-slate-100"><td className="px-6 py-4 font-medium text-slate-900">{item.empleado?.nombres} {item.empleado?.apellidos}</td><td className="px-6 py-4">{item.folio}</td><td className="px-6 py-4 text-xs">{new Date(item.fechaInicio).toLocaleDateString()} — {new Date(item.fechaFin).toLocaleDateString()} ({item.diasHabiles})</td><td className="px-6 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-0.5 text-xs font-medium">{estados[item.estado] || item.estado}</span></td><td className="px-6 py-4 text-right">{item.estado === 'EN_REVISION' ? <div className="flex justify-end gap-2"><button onClick={() => actualizar(item, 'solicitar-correccion')} className="inline-flex items-center rounded-lg bg-amber-50 px-3 py-1.5 text-xs text-amber-700"><MessageSquareReply className="mr-1 h-4 w-4" /> Devolver</button><button onClick={() => actualizar(item, 'aprobar')} className="inline-flex items-center rounded-lg bg-green-50 px-3 py-1.5 text-xs text-green-700"><CheckCircle2 className="mr-1 h-4 w-4" /> Aprobar</button><button onClick={() => actualizar(item, 'rechazar')} className="inline-flex items-center rounded-lg bg-red-50 px-3 py-1.5 text-xs text-red-700"><XCircle className="mr-1 h-4 w-4" /> Rechazar</button></div> : <span className="text-xs text-slate-400">—</span>}</td></tr>)}{!visibles.length && <tr><td colSpan="5" className="p-12 text-center text-slate-400"><FileText className="mx-auto mb-2 h-10 w-10 text-slate-300" />No hay solicitudes.</td></tr>}</tbody></table></div></div></div>;
}
